title = "go-blog-config"

[mysql]
host =  "127.0.0.1"
port =  3306
suffix = "charset=utf8&parseTime=true"
dbname = "go-blog"
username = "root"
password = "123456"
max_open_conns = 200
max_idle_conns = 50

[server]
port = ":8080"
